"""Execute a selected candidate and retain attributable technical evidence.

Readiness scores describe file/geometry checks, not visual or semantic quality.
Research metadata and user-provided fixtures are never generation evidence.
"""
from __future__ import annotations

import hashlib
from importlib import metadata
import json
import math
from pathlib import Path
import time
import uuid

from .evolution import Candidate

def evaluation_profile(capability: str, policy: dict | None = None) -> dict:
    """Domain-specific checks and scoring are declared by the evaluation policy."""
    from .evolution import load_policy

    profile = (policy if policy is not None else load_policy()).get("evaluation", {}).get(capability)
    if not profile:
        raise ValueError(f"No evaluation policy declared for capability {capability!r}")
    weights = profile.get("weights", {})
    if (not weights or any(type(w) not in (int, float) or not math.isfinite(w) or w < 0
                           for w in weights.values()) or sum(weights.values()) <= 0):
        raise ValueError(f"Invalid evaluation weights for capability {capability!r}")
    if not profile.get("metric") or not profile.get("required_checks"):
        raise ValueError(f"Evaluation {capability!r} requires a metric and required_checks")
    return profile


def file_hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _workdir(workdir: Path | None, capability: str) -> Path:
    from .core import locations
    base = Path(workdir) if workdir else locations.data_dir() / "probes" / capability
    # Every probe keeps its outputs and logs; no earlier candidate can inherit
    # another candidate's stale output or overwrite the evidence behind a score.
    path = base / uuid.uuid4().hex
    path.mkdir(parents=True)
    return path.resolve()


def _record(candidate: Candidate, output: Path, directory: Path, started: float,
            checks: dict, execution: dict, fixture: Path | None = None) -> Candidate:
    profile = evaluation_profile(candidate.capability)
    weights = profile["weights"]
    candidate.checks = checks
    candidate.score = round(sum(weights.get(k, 0) for k, ok in checks.items() if ok is True)
                            / sum(weights.values()), 4)
    proof = {
        "schema": 1, "kind": "candidate-generation",
        "candidate": candidate.name, "capability": candidate.capability,
        "spec": candidate.spec, "install_path": str(candidate.install_path.resolve()),
        "output": str(output.resolve()), "sha256": file_hash(output),
        "checks": checks, "score": candidate.score, "metric": profile["metric"],
        "visual_quality": "not_evaluated", "execution": execution,
        "duration_s": time.monotonic() - started,
        "fixture_sha256": file_hash(fixture) if fixture else None,
    }
    manifest = directory / "probe.json"
    manifest.write_text(json.dumps(proof, indent=2, ensure_ascii=False), encoding="utf-8")
    candidate.proof = {"manifest": str(manifest), "sha256": file_hash(manifest)}
    candidate.evidence = (f"Technical readiness: {candidate.score}; visual quality not evaluated. "
                          f"Generated by {candidate.spec}; proof: {manifest}")
    return candidate


def probe_3d(candidate: Candidate, *, fixture: Path, workdir: Path | None = None,
             **_kwargs) -> Candidate:
    """Generate with this candidate's runtime/model, not the first engine found."""
    from .core.engine3d import Engine3D, discover_engines, generate_mesh
    from .core.glb_validation import validate_glb

    if fixture is None:
        raise RuntimeError('3D probe requires an explicit image fixture; no quality score invented.')
    fixture = Path(fixture).resolve()
    if candidate.capability != "3d" or not fixture.is_file():
        raise RuntimeError("3D probe requires an image fixture and a 3D candidate")
    engine = None
    if candidate.install_path:
        root = candidate.install_path.resolve()
        engine = next((e for e in discover_engines()
                       if e.root.resolve() == root or e.repo.resolve() == root), None)
    if engine is None and (candidate.adapter.get("runner") or candidate.adapter.get("id")) == "hunyuan3d":
        from .core.bootstrap import ensure_3d_engine
        import os
        root = ensure_3d_engine()
        repo = root if (root / "hy3dshape").is_dir() else root / "Hunyuan3D-2.1"
        python = root / ("venv/Scripts/python.exe" if os.name == "nt" else "venv/bin/python")
        engine = Engine3D(candidate.spec, root, python, repo, (repo / "hy3dpaint").is_dir())
    if engine is None and (candidate.adapter.get('runner') or candidate.adapter.get('id')) == 'trellis2':
        from .core.pipeline import ensure_model
        root, python = ensure_model(candidate.spec, '3d')
        engine = Engine3D(candidate.spec, root, python, root / 'repo', True)
    if engine is None or not engine.available:
        raise RuntimeError("No implemented 3D runner for this candidate; another engine is not evidence")
    candidate.install_path = engine.root.resolve()
    directory = _workdir(workdir, "3d")
    output = directory / "probe.glb"
    started = time.monotonic()
    success, log = generate_mesh(engine, fixture, output, paint=True, model_ref=candidate.spec)
    (directory / "runtime.log").write_text(log, encoding="utf-8")
    if not success or not output.is_file():
        raise RuntimeError(f"Candidate generation failed; evidence: {directory}: {log[-1500:]}")
    validate_glb(output, require_textures=True)
    checks = {"output_nonempty": output.stat().st_size > 0, "mesh_valid": True, "has_texture": True}
    return _record(candidate, output, directory, started, checks,
                   {"runner": candidate.adapter.get('runner', 'hunyuan3d'), "model_ref": candidate.spec,
                    "runtime": str(engine.root.resolve())}, fixture)


def probe_image(candidate: Candidate, *, fixture: Path | None = None, prompt: str = "",
                workdir: Path | None = None) -> Candidate:
    """Generate and inspect a new image from the selected candidate.

    A legacy fixture argument remains accepted as input metadata only. It is
    never substituted for the candidate's own generated output.
    """
    from .core import pipeline

    if candidate.capability != "image":
        raise RuntimeError("Image probe requires an image candidate")
    directory = _workdir(workdir, "image")
    output = directory / "probe.png"
    started = time.monotonic()
    if candidate.install_path and (candidate.install_path / "model_index.json").is_file():
        model_ref = str(candidate.install_path.resolve())
    else:
        found = pipeline.ensure_model(candidate.spec, "image")
        if not found:
            raise RuntimeError("No image runtime available for selected candidate")
        candidate.install_path = found[0].resolve()
        model_ref = str(candidate.install_path)
    description = prompt or "A red ceramic sphere beside a blue cube on a white studio background"
    stage = pipeline.stage_generate_image(description, output, model_name=model_ref,
                                          model_spec=candidate.spec, seed=0)
    (directory / "runtime.log").write_text(stage.log, encoding="utf-8")
    if stage.status != "done" or stage.output != output or not output.is_file():
        raise RuntimeError(f"Candidate image generation failed; evidence: {directory}: {stage.log[-1500:]}")
    # Pillow is part of the managed image runtime, not assumed installed in CLI.
    from .core.bootstrap import python_engine
    import subprocess
    python = python_engine("images", ["torch", "diffusers", "transformers", "accelerate",
                                       "safetensors", "Pillow"])
    script = ("import json,sys; from PIL import Image; "
              "im=Image.open(sys.argv[1]); im.load(); "
              "lo,hi=im.convert('L').getextrema(); "
              "print(json.dumps({'width':im.width,'height':im.height,'range':hi-lo}))")
    validation = subprocess.run([str(python), "-c", script, str(output)], capture_output=True,
                                text=True, timeout=30, check=True)
    stats = json.loads(validation.stdout)
    limits = evaluation_profile("image")["limits"]
    checks = {"output_nonempty": output.stat().st_size > 0,
              "image_valid": stats["width"] >= limits["min_dimension"]
                             and stats["height"] >= limits["min_dimension"],
              "not_flat": stats["range"] > limits["min_luminance_range"]}
    if not all(checks.values()):
        raise RuntimeError(f"Candidate output failed image validity checks: {checks}; {directory}")
    return _record(candidate, output, directory, started, checks,
                   {"runner": "diffusers", "model_ref": candidate.spec,
                    "model_path": model_ref, "prompt": description},
                   Path(fixture) if fixture else None)


PROBES = {"3d": probe_3d, "image": probe_image}


def probe_for(capability: str):
    """Installed domain plugins may supply probes without changing the CLI.

    Entry points are executable code supplied by an installed package, never
    code obtained from a model search result.
    """
    entries = list(metadata.entry_points(group="jobia.probes", name=capability))
    if len(entries) > 1:
        raise RuntimeError(f"Multiple installed probes declare capability {capability!r}")
    if entries:
        probe = entries[0].load()
        if not callable(probe):
            raise RuntimeError(f"Installed probe for {capability!r} is not callable")
        return probe
    probe = PROBES.get(capability)
    if probe is None:
        raise RuntimeError(f"No probe implemented for capability {capability!r}")
    return probe


def run_probe(capability: str, candidate: Candidate, **kwargs) -> Candidate:
    if candidate.capability != capability:
        raise RuntimeError("Candidate capability does not match requested probe")
    from .adapters import AdapterRegistry

    runner, reason = AdapterRegistry().resolve(capability, candidate.spec)
    if runner is None:
        raise RuntimeError(reason)
    candidate.adapter = dict(runner.to_dict(), runner=runner.id, env=runner.environment())
    probe = probe_for(capability)
    # Research rows can carry arbitrary claimed scores; only this execution
    # creates the proof that the promotion gate will subsequently inspect.
    candidate.score, candidate.checks, candidate.proof = None, {}, {}
    return probe(candidate, **kwargs)


def main(argv: list[str] | None = None) -> int:
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("capability", help="Built-in capability or installed jobia.probes plugin")
    parser.add_argument("--model", required=True, help="Exact model reference to execute")
    parser.add_argument("--engine", type=Path, help="Installed candidate runtime or model directory")
    parser.add_argument("--fixture", type=Path)
    parser.add_argument("--prompt", default="")
    args = parser.parse_args(argv)
    candidate = Candidate(args.model, args.capability, args.model, "local",
                          install_path=args.engine)
    try:
        run_probe(args.capability, candidate, fixture=args.fixture, prompt=args.prompt)
    except Exception as exc:
        print(f"Probe failed: {exc}")
        return 1
    print(candidate.evidence)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
